# Generated by Django 6.1.1 on 2026-09-12 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título do Curso')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título da Lição')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('content', models.TextField(verbose_name='Conteúdo Teórico / Instruções')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='modules.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título do Desafio')),
                ('instructions', models.TextField(verbose_name='Enunciado do Desafio')),
                ('language', models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('sql', 'SQL'), ('quiz', 'Múltipla Escolha / Quiz')], default='python', max_length=20)),
                ('initial_code', models.TextField(blank=True, verbose_name='Código Inicial (Boilerplate)')),
                ('expected_output', models.TextField(blank=True, verbose_name='Saída ou Resposta Esperada')),
                ('points', models.IntegerField(default=10, verbose_name='Pontuação/XP')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='modules.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(db_index=True, max_length=128, verbose_name='UID Firebase do Aluno')),
                ('completed', models.BooleanField(default=False, verbose_name='Concluído')),
                ('submitted_code', models.TextField(blank=True, verbose_name='Código Submetido')),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.challenge')),
            ],
            options={
                'unique_together': {('firebase_uid', 'challenge')},
            },
        ),
    ]
