# Generated by Django 6.1.1 on 2026-10-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroReplanejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.CharField(max_length=255, verbose_name='Nome da Escola')),
                ('tipo_documento', models.CharField(choices=[('DISCIPLINA_TECNICA', 'Disciplina Técnica'), ('MAPAO_CONSELHO', 'Mapão do Conselho (FGB)')], default='DISCIPLINA_TECNICA', max_length=50)),
                ('bimestre', models.CharField(default='3º Bimestre', max_length=50, verbose_name='Bimestre')),
                ('disciplina', models.CharField(max_length=150, verbose_name='Disciplina / Aba')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número da Chamada')),
                ('situacao', models.CharField(default='Ativo', max_length=50, verbose_name='Situação')),
                ('nome_aluno', models.CharField(db_index=True, max_length=255, verbose_name='Nome do Estudante')),
                ('trabalho', models.FloatField(default=0.0, verbose_name='Nota Trabalho')),
                ('atividades', models.FloatField(default=0.0, verbose_name='Nota Atividades')),
                ('prova', models.FloatField(default=0.0, verbose_name='Nota Prova')),
                ('prova_paulista', models.FloatField(default=0.0, verbose_name='Nota Prova Paulista')),
                ('media_final', models.FloatField(db_index=True, default=0.0, verbose_name='Média Final')),
                ('faltas_totais', models.FloatField(default=0.0, verbose_name='Total Faltas')),
                ('frequencia_pct', models.CharField(default='100%', max_length=20, verbose_name='Frequência (%)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Replanejamento',
                'verbose_name_plural': 'Registros de Replanejamento',
            },
        ),
    ]
