# Generated by Django 6.1.1 on 2026-09-25 20:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_barras', models.CharField(db_index=True, max_length=32, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_estoque', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('ncm', models.CharField(default='00000000', max_length=8)),
                ('cest', models.CharField(blank=True, max_length=7, null=True)),
                ('cfop', models.CharField(default='5102', max_length=4)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
